### ISSUE TITLE
Custom topics for direct messages

### ISSUE THREAD

**Issue by vicglarson** [xmtp/xmtp-js#179]
Could you please make message topic customizable with js Client interface.

Ability to replace this function with callback d be enough:
https://github.com/xmtp/xmtp-js/blob/3659a35b523366f717b2bdaa4bc8e332da5a7e1a/src/utils.ts#L6

I'm triyng to filter messages by content but now there are no any good approach.

Custom topics are enough for me.

**Comment by neekolas** [comment]
Excellent timing on this question.

We don't think arbitrarily changing topic names is the right solution for this problem for three reasons:
1. There is a coordination problem of having the other side know which topics to look for and read from
2. There is the possibility of collisions between apps
3. There is a security issue where we are currently using the address in the topic name to validate that the message was sent from the address attested in the message headers. Without that, someone might be able to inject themselves into a private conversation.

The good news is that we have a different proposal for message filtering, which I'm hoping to share in our Github discussions later today. I'll tag you on it once it's live. Would love comments and feedback

**Comment by utgarda** [comment]
Hi @neekolas! Thanks for giving it a thought.

>1. There is a coordination problem of having the other side know which topics to look for and read from  

That's happens around the start of building a protocol on top of XMTP - apps have to extract their own meaning from what's sent in a message, instead of showing them to users raw. And if an app uses more than one topic for interaction that can happen between two clients - like in our case, game moves, then they have to use filtering by field. I'm not saying it's necessarily easier to do it inside XMTP, just explaining why we want it.

> 2. There is the possibility of collisions between apps 

That's exactly what we're getting without this dream feature. Chatting in xmtp.chat in parrallel with playing a turn-based game in our app using the same addresses was dropping plain-text chitchat messages in between properly formatted app messages, and familiar-by-weird-to-be-seen-here JSON in a chat window. In fact, we're now using the example example-chat-react as a debug tool. 

Adding topic IDs as suffixes

```js
return buildContentTopic(`dm-${members.join('-')}`)
```
[buildDirectMessageTopic](https://github.com/xmtp/xmtp-js/blob/3659a35b523366f717b2bdaa4bc8e332da5a7e1a/src/utils.ts#L12)

to, say, `dm-0x3Be65C389F095aaa50D0b0F3801f64Aa0258940b-0x5Ce2D6FDb0548234c376348aaB6463378b7B7af3` would allow treating the first part of it the same way - this way no app can alter `dm-` prefix or addresses, and can't hijack conversations.

On the other hand, this would allow apps avoid breaking each other's message flow without building additional filtering on each side inserting app+topic IDs in their messages.  

> 3. There is a security issue where we are currently using the address in the topic name

That's a very natural place for addresses, so they should stay in there - if apps can't build the topic ID themselves, but just a suffix to the protocol-defined topic IDs, they can't hijack other users' topics. I understand the concern and why one would rather not mix implementation of nice-to-have features with the code responsible for privacy.

Still, custom topics would be amazingly useful for building custom communication protocols on top of XMTP that already handles the most wanted functionality.

**Comment by utgarda** [comment]
Is it the right thing to do - sending app messages through `dm-0x...-0x..` topic, is there another way?

**Comment by neekolas** [comment]
Take a look at this Github Discussions post, which outlines our vision for how multiple chats can work within XMTP. https://github.com/orgs/xmtp/discussions/12

**Comment by neekolas** [comment]
We're actively working on implementing the feature. It'll be rolling out this month.

**Comment by saulmc** [comment]
Resolving this issue as conversation IDs as discussed in https://github.com/orgs/xmtp/discussions/12 were released with https://github.com/xmtp/xmtp-js/compare/v6.8.3...v7.0.0!

/cc @vicglarson @utgarda
