### ISSUE TITLE
Feature request: Ability to Create Custom XMTP Topics from Client-Side

### ISSUE THREAD

**Issue by Im-Kunal-13** [xmtp/xmtp-js#327]
### Is your feature request related to a problem ?

There are instances when having supplementary information about a conversation can prove advantageous for users and facilitate the integration of certain functionalities dependent on it. From a security standpoint, it would be more favorable to have a mechanism to store such information within the XMTP network itself rather than any external location

### Describe the solution to the problem

Certainly, custom XMTP topics can be utilized to store pertinent information that can aid in achieving this objective, while simultaneously allowing both parties to share the necessary information in a secure and decentralized manner. By utilizing custom XMTP topics, users can securely store and share relevant data within the XMTP network itself, thus enhancing the overall messaging experience while also ensuring the protection of user data

### Describe the uses cases for the feature

For instance, we can store information regarding opt-in and opt-out preferences for read receipts as well as enable or disable only a subset of states for it through custom topics, which would help users manage their messaging preferences and improve their messaging experience

**Comment by neekolas** [comment]
I definitely see the need for us to solve for these use-cases. Private storage would unlock a lot of cool features missing on the network. 

I think this requires a more complete solution than just being able to publish to custom topics, though. To avoid chaos, we would want to have a well-defined encryption scheme for these topics and write-restrictions in place so that other users could not SPAM or DOS the topics. 

Definitely something we are investigating and looking at including in a future release.
